/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as StreamersRouteImport } from './routes/streamers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DevkRouteImport } from './routes/devk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ApiPublicDiscordXpRouteImport } from './routes/api/public/discord.xp'
import { Route as ApiPublicDiscordPointsRouteImport } from './routes/api/public/discord.points'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamersRoute = StreamersRouteImport.update({
  id: '/streamers',
  path: '/streamers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DevkRoute = DevkRouteImport.update({
  id: '/devk',
  path: '/devk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordXpRoute = ApiPublicDiscordXpRouteImport.update({
  id: '/api/public/discord/xp',
  path: '/api/public/discord/xp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordPointsRoute = ApiPublicDiscordPointsRouteImport.update({
  id: '/api/public/discord/points',
  path: '/api/public/discord/points',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/devk': typeof DevkRoute
  '/games': typeof GamesRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/shop': typeof ShopRoute
  '/streamers': typeof StreamersRoute
  '/tournaments': typeof TournamentsRoute
  '/s/$slug': typeof SSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/discord/points': typeof ApiPublicDiscordPointsRoute
  '/api/public/discord/xp': typeof ApiPublicDiscordXpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/devk': typeof DevkRoute
  '/games': typeof GamesRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/shop': typeof ShopRoute
  '/streamers': typeof StreamersRoute
  '/tournaments': typeof TournamentsRoute
  '/s/$slug': typeof SSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/discord/points': typeof ApiPublicDiscordPointsRoute
  '/api/public/discord/xp': typeof ApiPublicDiscordXpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/devk': typeof DevkRoute
  '/games': typeof GamesRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/shop': typeof ShopRoute
  '/streamers': typeof StreamersRoute
  '/tournaments': typeof TournamentsRoute
  '/s/$slug': typeof SSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/discord/points': typeof ApiPublicDiscordPointsRoute
  '/api/public/discord/xp': typeof ApiPublicDiscordXpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/devk'
    | '/games'
    | '/hall-of-fame'
    | '/leaderboard'
    | '/shop'
    | '/streamers'
    | '/tournaments'
    | '/s/$slug'
    | '/u/$userId'
    | '/api/public/discord/points'
    | '/api/public/discord/xp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/devk'
    | '/games'
    | '/hall-of-fame'
    | '/leaderboard'
    | '/shop'
    | '/streamers'
    | '/tournaments'
    | '/s/$slug'
    | '/u/$userId'
    | '/api/public/discord/points'
    | '/api/public/discord/xp'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/devk'
    | '/games'
    | '/hall-of-fame'
    | '/leaderboard'
    | '/shop'
    | '/streamers'
    | '/tournaments'
    | '/s/$slug'
    | '/u/$userId'
    | '/api/public/discord/points'
    | '/api/public/discord/xp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DevkRoute: typeof DevkRoute
  GamesRoute: typeof GamesRoute
  HallOfFameRoute: typeof HallOfFameRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ShopRoute: typeof ShopRoute
  StreamersRoute: typeof StreamersRoute
  TournamentsRoute: typeof TournamentsRoute
  SSlugRoute: typeof SSlugRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiPublicDiscordPointsRoute: typeof ApiPublicDiscordPointsRoute
  ApiPublicDiscordXpRoute: typeof ApiPublicDiscordXpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamers': {
      id: '/streamers'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof StreamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devk': {
      id: '/devk'
      path: '/devk'
      fullPath: '/devk'
      preLoaderRoute: typeof DevkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/xp': {
      id: '/api/public/discord/xp'
      path: '/api/public/discord/xp'
      fullPath: '/api/public/discord/xp'
      preLoaderRoute: typeof ApiPublicDiscordXpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/points': {
      id: '/api/public/discord/points'
      path: '/api/public/discord/points'
      fullPath: '/api/public/discord/points'
      preLoaderRoute: typeof ApiPublicDiscordPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DevkRoute: DevkRoute,
  GamesRoute: GamesRoute,
  HallOfFameRoute: HallOfFameRoute,
  LeaderboardRoute: LeaderboardRoute,
  ShopRoute: ShopRoute,
  StreamersRoute: StreamersRoute,
  TournamentsRoute: TournamentsRoute,
  SSlugRoute: SSlugRoute,
  UUserIdRoute: UUserIdRoute,
  ApiPublicDiscordPointsRoute: ApiPublicDiscordPointsRoute,
  ApiPublicDiscordXpRoute: ApiPublicDiscordXpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
